name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install docker.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install docker.io

      - name: Deploy to EC2
        run: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
          sudo docker stop my-html-app || true
          sudo docker rm my-html-app || true
          sudo docker run -d --name my-html-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
